### ISSUE TITLE
Manifest in release v0.0.5 contains v0.0.4 image tag

### ISSUE THREAD

**Issue by MarnixBouhuis** [dragonflydb/dragonfly-operator#74]
The `v0.0.5` release contains the wrong image tag inside the `manifests/dragonfly-operator.yaml` file. 

When viewing the file as in tag `v0.0.5` (https://github.com/dragonflydb/dragonfly-operator/blob/v0.0.5/manifests/dragonfly-operator.yaml#L463) the following shows: https://github.com/dragonflydb/dragonfly-operator/blob/f4cc58c3d7a7bd3d84d021e615ec0041c886ecd1/manifests/dragonfly-operator.yaml#L463

**Comment by Pothulapati** [comment]
Hey @MarnixBouhuis, Thanks for raising the issue.

Actually, The plan for manifests was to have the latest image manifests available that folks could use from the repo, and not tie it per commit (like you are expecting). This is why we also didn't release these as part of the release Github artifacts.

But, I agree with your expectation here and I will make it so that we update the manifests as a release process step from the next release.

**Comment by Pothulapati** [comment]
So, We strarted following this pattern and the last two releases (atleast) have the matching versions in the files. So, Closing this.
